FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/openshift/gcp-filestore-csi-driver-operator
COPY . .
RUN make

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/openshift/gcp-filestore-csi-driver-operator/gcp-filestore-csi-driver-operator /usr/bin/
ENTRYPOINT ["/usr/bin/gcp-filestore-csi-driver-operator"]
LABEL io.k8s.display-name="OpenShift GCP Filestore CSI Driver Operator" \
	io.k8s.description="The GCP Filestore CSI Driver Operator installs and maintains the GCP Filestore CSI Driver on a cluster."
